language: node_js
cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/.yarn-cache"
    - node_modules
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - sysconfcpus
    - test/elm-stuff
before_install:
  - npm install -g yarn
  # Faster compile of Elm on Travis.
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
install:
  - yarn
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 yarn build
script:
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 yarn test
before_deploy:
  - openssl aes-256-cbc -K $encrypted_6d2f7c519862_key -iv $encrypted_6d2f7c519862_iv -in id_rsa_caronaboard.enc -out id_rsa_caronaboard -d
deploy:
  provider: script
  script: "./deploy.sh"
  on:
    branch: replace-snap-with-travis
