language: node_js
cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/.yarn-cache"
    - node_modules
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - tests/elm-stuff/build-artifacts
    - tests/elm-stuff/packages
before_install:
  - npm install -g yarn
install:
  - yarn
  - yarn build
script:
  - yarn test
deploy:
  provider: script
  script: "./deploy.sh"
  skip_cleanup: true
  on:
    branch: master
